### ISSUE TITLE
UserStories

### ISSUE THREAD

**Issue by akkad88** [mif-sge/einkaufszentrum#4]

**Comment by meysameh** [comment]
| **Use-Case**| **Als**|   **möchte ich**   | , **so dass** | **Erfüllt, wenn** |
|:-----|:----------:|:-------------------|:-------------|:---------|
| UC-MC-1 | Kunde | die Öffnungszeiten anschauen | ich weiß, wann das Einkaufzentrum geöffnet & geschlossen wird. | Öfnungszeiten angezeigt werden. |
| UC-MC-2 | Kunde | die Temperature anschauen | ich weiß, wie hoch die Temperatur ist. | Die Temperatur angezeigt wird. |
| UC-MC-3 | Kunde | eine Übersicht über die freie Parkplätze haben | ich weiß, wo die freie Parkplätze sind. | die freie Parkplätze in der Anwendung angezeigt werden. |
| UC-MC-4(3.1) | Kunde | nach die Gebühren pro Stunde erkundigen kann | das Auto auf einem freien Parkplatz parken kann. | die Gebühren in der Anwendung angezeigt werden. |
| UC-MC-5 | Admin | das Smart-Display der Öffnungszeiten verwalten | die Kunden eine Übersicht über die Zeit erhalten. | die Öffnungszeiten angezeigt werden.|
| UC-MC-6 | Admin | den Temperaturemete überprüfen | die Innentemperatur entsprechend der Außentemperatur von der Heizungssteuerung eingestellt wird. | die Temperature den kunden angezeigt wird. |
| UC-MC-7 | Admin | die Parkfläche überprüfen |  die Informationen der Parkplätze aktualisiert werden . | die freie Parkpläzte und Gebüren für Kunden angezeigt werden. |
| UC-MC-8 | Organismus | die Öffnungszeiten-Informationen richtig bekommen | ich aller Bürger die Öffnungszeiten weiterleiten kann. | die Öffnungszeiten richtig angezeigt werden. |
| UC-MC-9 | Organismus | eine optimierte Temperatur für das Einkaufszentrum berechnet bekommen | ich die Heizungssteuerung optimieren kann. | Optimierte Temperatur wird eingestellet. |
| UC-MC-10 | Organismus | die freie/genutzte Parkplätze der Parkfläche berechnet bekommen |ich die Parkfläche optimieren kann. |  die freie/genutzte Parkplätze der Parkfläche berechnet werden. |

**Comment by meysameh** [comment]
| **Use-Case**| **Als**|   **möchte ich**   | , **so dass** | **Erfüllt, wenn** |
|:-----|:----------:|:-------------------|:-------------|:---------|
| UC-MC-1 | Kunde | die Öffnungszeiten anschauen | ich weiß, wann das Einkaufzentrum geöffnet & geschlossen wird. | Öfnungszeiten angezeigt werden. |
| UC-MC-2 | Kunde | die Temperature anschauen | ich weiß, wie hoch die Temperatur ist. | Die Temperatur angezeigt wird. |
| UC-MC-3.1 | Kunde | eine Übersicht über die freie Parkplätze haben | ich weiß, wo die freie Parkplätze sind. | die freie Parkplätze in der Anwendung angezeigt werden. |
| UC-MC-3.2 | Kunde | nach die Gebühren pro Stunde erkundigen kann | das Auto auf einem freien Parkplatz parken kann. | die Gebühren in der Anwendung angezeigt werden. |
| UC-MC-4 | Admin | das Smart-Display der Öffnungszeiten verwalten | die Kunden eine Übersicht über die Zeit erhalten. | die Öffnungszeiten angezeigt werden.|
| UC-MC-5 | Admin | den Temperaturemete überprüfen | die Innentemperatur entsprechend der Außentemperatur von der Heizungssteuerung eingestellt wird. | die Temperature den kunden angezeigt wird. |
| UC-MC-6 | Admin | die Parkfläche überprüfen |  die Informationen der Parkplätze aktualisiert werden . | die freie Parkpläzte und Gebüren für Kunden angezeigt werden. |
| UC-MC-7 | Organismus | die Öffnungszeiten-Informationen richtig bekommen | ich aller Bürger die Öffnungszeiten weiterleiten kann. | die Öffnungszeiten richtig angezeigt werden. |
| UC-MC-8 | Organismus | eine optimierte Temperatur für das Einkaufszentrum berechnet bekommen | ich die Heizungssteuerung optimieren kann. | Optimierte Temperatur wird eingestellet. |
| UC-MC-9 | Organismus | die freie/genutzte Parkplätze der Parkfläche berechnet bekommen |ich die Parkfläche optimieren kann. |  die freie/genutzte Parkplätze der Parkfläche berechnet werden. |

**Comment by Zakor11** [comment]
please upload this as .md-file

**Comment by akkad88** [comment]
#4 UseStories
