### ISSUE TITLE
Eventspezifikation

### ISSUE THREAD

**Issue by Zakor11** [mif-sge/einkaufszentrum#9]
Spezifiziere Events nach dem Dokument in Organisation/api

**Comment by Zakor11** [comment]
Bitte einmal das Dokument anpassen, sodass es ähnlich wie hier aussieht:
https://github.com/mif-sge/organisation/blob/master/docs/api/Event_Specification.md

**Comment by HalaSw** [comment]
@Zakor11 
jetzt alles in Ordnung ?

**Comment by Zakor11** [comment]
Soll mir an der Stelle reichen.
